-- MySQL Script generated by MySQL Workbench
-- Mon May  8 15:14:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`office` (
  `office_id` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT '机构编码',
  `name` VARCHAR(60) NULL COMMENT '机构名称',
  `short_name` VARCHAR(60) NULL COMMENT '机构简称',
  `en_name` VARCHAR(60) NULL COMMENT '英文名称',
  `office_code` VARCHAR(20) NULL COMMENT '机构代码',
  `owner` VARCHAR(45) NULL COMMENT '负责人',
  `office_type` VARCHAR(45) NULL COMMENT '机构类别',
  `office_level` VARCHAR(45) NULL COMMENT '机构行政级别',
  `office_class` VARCHAR(45) NULL COMMENT '机构隶属层级',
  `last_office` VARCHAR(45) NULL COMMENT '上级主管机关',
  `last_dept` VARCHAR(45) NULL COMMENT '上级主管部门',
  `tel` VARCHAR(45) NULL COMMENT '联系电话',
  `fox` VARCHAR(40) NULL COMMENT '传真号码',
  `email` VARCHAR(60) NULL COMMENT '电子邮箱',
  `zip` VARCHAR(6) NULL COMMENT '邮编',
  `address` VARCHAR(200) NULL COMMENT '地址',
  PRIMARY KEY (`office_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `staff_id` VARCHAR(20) NOT NULL COMMENT '人员编码',
  `name` VARCHAR(50) NULL COMMENT '姓名',
  `sex` BIT(1) NULL COMMENT '性别',
  `birthday` DATETIME NULL COMMENT '出生日期',
  `id_card` VARCHAR(18) NULL COMMENT '身份证号',
  `nation` VARCHAR(2) NULL COMMENT '民族',
  `political` VARCHAR(45) NULL COMMENT '政治面貌',
  `married` VARCHAR(45) NULL COMMENT '婚姻状况',
  `photo` VARCHAR(45) NULL COMMENT '照片',
  `university` VARCHAR(45) NULL COMMENT '毕业院校',
  `education` VARCHAR(45) NULL COMMENT '学历',
  `degree` VARCHAR(45) NULL COMMENT '最高学位',
  `profession` VARCHAR(45) NULL COMMENT '专业',
  `office_id` VARCHAR(45) NULL COMMENT '所属机构',
  `job` VARCHAR(45) NULL COMMENT '职务',
  `staffing` VARCHAR(45) NULL COMMENT '人员编制',
  `work_time` VARCHAR(45) NULL COMMENT '参加工作时间',
  `mobile` VARCHAR(20) NULL COMMENT '手机号码',
  `phone` VARCHAR(40) NULL COMMENT '联系电话',
  `email` VARCHAR(100) NULL COMMENT '电子邮箱',
  `address` VARCHAR(200) NULL COMMENT '住址',
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invest` (
  `acedt_serial` VARCHAR(20) NOT NULL COMMENT '委托编号',
  `bm_type` VARCHAR(2) NULL COMMENT '矫正人员类型',
  `bm_name` VARCHAR(20) NULL COMMENT '罪犯姓名',
  `bm_idcard` VARCHAR(18) NULL COMMENT '罪犯身份证号',
  `bm_sex` VARCHAR(2) NULL COMMENT '性别',
  `bm_birthday` VARCHAR(45) NULL COMMENT '罪犯出生日期',
  `bm_address` VARCHAR(45) NULL COMMENT '罪犯居住地址',
  `bm_company` VARCHAR(45) NULL COMMENT '罪犯工作单位',
  `charge` VARCHAR(45) NULL COMMENT '罪名',
  `team` VARCHAR(45) NULL COMMENT '原判刑期',
  `addn_pun` VARCHAR(45) NULL COMMENT '附加刑',
  `judg_organ` VARCHAR(45) NULL COMMENT '判决机关',
  `judg_date` DATETIME NULL COMMENT '判决日期',
  `client` VARCHAR(45) NULL COMMENT '委托单位',
  `inve_book` VARCHAR(45) NULL COMMENT '委托调查书',
  `respondent` VARCHAR(45) NULL COMMENT '被调查人姓名',
  `bm_relation` VARCHAR(45) NULL COMMENT '与罪犯关系',
  `inve_items` VARCHAR(45) NULL COMMENT '调查事项',
  `inve_time` VARCHAR(45) NULL COMMENT '调查时间',
  `inve_addr` VARCHAR(45) NULL COMMENT '调查地点',
  `corr_type` VARCHAR(45) NULL COMMENT '矫正类别',
  `inve_company` VARCHAR(45) NULL COMMENT '调查单位（所）',
  `inve_company2` VARCHAR(45) NULL COMMENT '调查单位（县区所）',
  `investigator` VARCHAR(45) NULL COMMENT '调查人',
  `reviewer` VARCHAR(45) NULL COMMENT '调查意见审核人',
  `sugg_book` VARCHAR(45) NULL COMMENT '调查评估意见书',
  `condition` VARCHAR(45) NULL COMMENT '采用情况',
  PRIMARY KEY (`acedt_serial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`badman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`badman` (
  `badman_id` INT NOT NULL,
  `badman_code` VARCHAR(20) NULL COMMENT '矫正人员编号',
  `mgr_class` VARCHAR(2) NULL COMMENT '管理对象类别',
  `name` VARCHAR(20) NULL COMMENT '姓名',
  `old_name` VARCHAR(20) NULL COMMENT '曾用名',
  `sex` VARCHAR(2) NULL COMMENT '性别',
  `nation` VARCHAR(20) NULL COMMENT '民族',
  `id_type` VARCHAR(20) NULL COMMENT '证件类型',
  `id_number` VARCHAR(18) NULL COMMENT '证件号码',
  `birthday` DATETIME NULL COMMENT '生日',
  `have_pass` TINYINT NULL COMMENT '有无护照',
  `pass_number` VARCHAR(20) NULL COMMENT '护照号码',
  `have_hp` TINYINT NULL COMMENT '有无回乡证',
  `hp_number` VARCHAR(20) NULL COMMENT '回乡证号码',
  `have_mtp` TINYINT NULL COMMENT '有无台胞证',
  `mtp_number` VARCHAR(20) NULL COMMENT '台胞证号码',
  `education` VARCHAR(20) NULL COMMENT '文化程度',
  `health` INT NULL COMMENT '健康状况',
  `health_detail` VARCHAR(100) NULL COMMENT '具体健康状况',
  `have_infe_hist` TINYINT NULL COMMENT '是否有传染病史',
  `infe_hist` VARCHAR(100) NULL COMMENT '具体传染病',
  `is_ment_health` TINYINT NULL COMMENT '心理是否健康',
  `ment_health` VARCHAR(100) NULL COMMENT '心理健康',
  `appr_organ` VARCHAR(50) NULL COMMENT '鉴定机构',
  `political` VARCHAR(20) NULL COMMENT '政治面貌',
  `old_political` VARCHAR(20) NULL COMMENT '原政治面貌',
  `married` VARCHAR(20) NULL COMMENT '婚姻状况',
  `work_status` VARCHAR(20) NULL COMMENT '就业就学情况',
  `old_company` VARCHAR(100) NULL,
  `company` VARCHAR(100) NULL,
  `compnay_phone` VARCHAR(40) NULL,
  `personal_phone` VARCHAR(40) NULL,
  `is_social_relations` TINYINT NULL COMMENT '有无社会关系',
  `photo` BLOB NULL COMMENT '照片',
  `home_province` VARCHAR(20) NULL,
  `home_city` VARCHAR(20) NULL,
  `home_county` VARCHAR(20) NULL,
  `home_town` VARCHAR(20) NULL,
  `home_addr` VARCHAR(100) NULL,
  `register_province` VARCHAR(20) NULL,
  `register_city` VARCHAR(20) NULL,
  `register_county` VARCHAR(20) NULL,
  `register_town` VARCHAR(20) NULL,
  `register_addr` VARCHAR(100) NULL,
  `inve_orgn` VARCHAR(50) NULL,
  `hold_date` DATETIME NULL,
  `put_date` DATETIME NULL,
  `catch_office` VARCHAR(50) NULL COMMENT '逮捕机关',
  `catch_date` DATETIME NULL COMMENT '逮捕日期',
  `close_date` DATETIME NULL COMMENT '侦结日期',
  `prosecutor` VARCHAR(50) NULL COMMENT '自投人',
  `indict_number` VARCHAR(50) NULL COMMENT '起诉书编号',
  `indict_date` DATETIME NULL COMMENT '起诉日期',
  `judg_appr` VARCHAR(100) NULL COMMENT '审判机关',
  `judg_code` VARCHAR(50) NULL,
  `judg_date` DATETIME NULL,
  `exec_date_number` VARCHAR(100) NULL,
  `custody_place` VARCHAR(50) NULL,
  `exec_date` DATETIME NULL,
  `decs_organ` VARCHAR(50) NULL COMMENT '社区矫正决定机关',
  `doc_type_number` VARCHAR(100) NULL,
  `doc_date` DATETIME NULL,
  `main_crim_facts` VARCHAR(500) NULL COMMENT '主要犯罪事实',
  `admin_punish` VARCHAR(500) NULL,
  `crim_punish` VARCHAR(500) NULL,
  `corr_type` VARCHAR(2) NULL,
  `corr_limit` VARCHAR(20) NULL,
  `corr_begin_date` DATETIME NULL,
  `corr_end_date` DATETIME NULL,
  `crime_type` INT NULL,
  `crime_name` INT NULL,
  `orig_punish` VARCHAR(50) NULL,
  `addt_punish` VARCHAR(2) NULL,
  `fixed_term_limit` INT NULL,
  `term_begin_date` DATETIME NULL,
  `term_end_date` DATETIME NULL,
  `depr_limit` VARCHAR(100) NULL COMMENT '剥夺政治权利期限',
  `depr_begin_date` DATETIME NULL COMMENT '剥夺政治权利开始日期',
  `depr_end_date` DATETIME NULL COMMENT '剥夺政治权利结束日期',
  `depr_police_place` VARCHAR(50) NULL COMMENT '公安机关名称',
  `receiver` VARCHAR(50) NULL COMMENT '接收人',
  `turn_date` DATETIME NULL COMMENT '移交日期',
  `have4S` TINYINT NULL COMMENT '是否有四史',
  `have_old_bm` TINYINT NULL COMMENT '是否累惯犯',
  `have3S` TINYINT NULL COMMENT '是否三涉',
  `is_recrime` TINYINT NULL COMMENT '是否共同犯罪',
  `is_no_order` TINYINT NULL COMMENT '是否被宣传禁止令',
  `text_no_order` VARCHAR(500) NULL COMMENT '禁止令内容',
  `begin_date_noorder` DATETIME NULL COMMENT '禁止期限开始日期',
  `end_date_noorder` DATETIME NULL COMMENT '禁止期限结束日期',
  `recv_book_date` DATETIME NULL COMMENT '法律文书找到日期',
  `recv_mode` INT NULL COMMENT '接收方式',
  `rpt_situ` TINYINT NULL COMMENT '报到情况',
  `is_corr_group` TINYINT NULL COMMENT '是否建立矫正小组',
  `person_comp` TINYINT NULL COMMENT '矫正小组人员组成情况',
  `is_pos` TINYINT NULL COMMENT '是否使用定位',
  `eq_type` INT NULL COMMENT '终端类型',
  `imei` VARCHAR(20) NULL COMMENT '终端号码',
  PRIMARY KEY (`badman_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resume` (
  `resume_id` INT NOT NULL COMMENT '矫正人员编号',
  `badman_id` VARCHAR(45) NULL COMMENT '矫正人员编号',
  `begin_date` DATETIME NULL COMMENT '起时',
  `end_date` DATETIME NULL COMMENT '止日',
  `company` VARCHAR(50) NULL COMMENT '所在单位',
  `job` VARCHAR(20) NULL COMMENT '职务',
  PRIMARY KEY (`resume_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`relations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`relations` (
  `relations_id` INT NOT NULL,
  `badman_id` VARCHAR(45) NULL COMMENT '矫正人员编号',
  `relations` VARCHAR(45) NULL COMMENT '关系',
  `name` VARCHAR(45) NULL COMMENT '姓名',
  `company` VARCHAR(45) NULL COMMENT '所在单位',
  `addr` VARCHAR(45) NULL COMMENT '家庭住址',
  `phone` VARCHAR(45) NULL COMMENT '联系电话',
  PRIMARY KEY (`relations_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escort` (
  `escort_id` INT NOT NULL,
  `badman_id` VARCHAR(50) NULL COMMENT '矫正人员编号',
  `police_name` VARCHAR(50) NULL COMMENT '警察姓名',
  `company_job` VARCHAR(200) NULL COMMENT '单位及职务',
  `escort_date` DATETIME NULL COMMENT '押送日期',
  PRIMARY KEY (`escort_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accomplice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accomplice` (
  `accomplice_id` INT NOT NULL,
  `badman_id` VARCHAR(45) NULL COMMENT '矫正人员编号',
  `name` VARCHAR(45) NULL COMMENT '姓名',
  `sex` TINYINT NULL COMMENT '性别',
  `birthday` DATETIME NULL COMMENT '生日',
  `crime_name` VARCHAR(45) NULL COMMENT '罪名',
  `prison` VARCHAR(200) NULL,
  PRIMARY KEY (`accomplice_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`region_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`region_in` (
  `region_in_id` INT NOT NULL,
  `apply_place` VARCHAR(45) NULL,
  `apply_date` DATETIME NULL,
  `apply_begin_time` DATETIME NULL,
  `apply_end_time` DATETIME NULL,
  `apply_reasons` VARCHAR(200) NULL,
  `office_auditor` VARCHAR(45) NULL COMMENT '所审核人',
  `office_audit_time` DATETIME NULL COMMENT '所审核时间',
  `office_audit_view` VARCHAR(200) NULL COMMENT '所审核意见',
  `higher_auditor` VARCHAR(45) NULL COMMENT '局审批人',
  `higher_audit_time` DATETIME NULL COMMENT '局审批时间',
  `higher_audit_view` VARCHAR(200) NULL COMMENT '局审批意见',
  PRIMARY KEY (`region_in_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apply_out`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apply_out` (
  `apply_out_id` INT NOT NULL,
  `badman_id` VARCHAR(45) NULL COMMENT '矫正人员编号',
  `apply_date` DATETIME NULL COMMENT '申请时间',
  `province` VARCHAR(20) NULL COMMENT '所在省',
  `city` VARCHAR(20) NULL COMMENT '所在地',
  `county` VARCHAR(20) NULL COMMENT '所在县',
  `town` VARCHAR(20) NULL COMMENT '所在镇',
  `addr` VARCHAR(100) NULL COMMENT '目的地明细',
  `out_reason` VARCHAR(200) NULL COMMENT '外出理由',
  `out_days` VARCHAR(45) NULL COMMENT '外出天数',
  `out_begin_time` DATETIME NULL,
  `out_end_time` DATETIME NULL,
  `office_auditor` VARCHAR(45) NULL COMMENT '所审核时间',
  `office_audit_time` DATETIME NULL,
  `office_audit_view` VARCHAR(45) NULL,
  `higher_auditor` VARCHAR(45) NULL,
  `higher_audit_time` DATETIME NULL,
  `higher_audit_view` VARCHAR(200) NULL,
  PRIMARY KEY (`apply_out_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`addr_change`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`addr_change` (
  `addr_change_id` INT NOT NULL,
  `badman_id` VARCHAR(45) NULL COMMENT '矫正人员编号',
  `apply_time` DATETIME NULL COMMENT '申请时间',
  `in_province` VARCHAR(45) NULL COMMENT '迁入省',
  `in_city` VARCHAR(45) NULL COMMENT '迁入市',
  `in_county` VARCHAR(45) NULL COMMENT '迁入县',
  `in_town` VARCHAR(45) NULL COMMENT '迁入镇',
  `in_addr` VARCHAR(45) NULL COMMENT '迁入地明细',
  `change_reason` VARCHAR(45) NULL COMMENT '变更理由',
  `office_auditor` VARCHAR(45) NULL COMMENT '所审核人',
  `office_audit_time` DATETIME NULL COMMENT '所审核时间',
  `office_audit_view` VARCHAR(45) NULL COMMENT '所审核意见',
  `higher_auditor` VARCHAR(45) NULL COMMENT '上级审核人',
  `higher_auditor_time` DATETIME NULL COMMENT '上级审核时间',
  `higher_auditor_view` VARCHAR(45) NULL COMMENT '上级审核意见',
  PRIMARY KEY (`addr_change_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`verify_evd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`verify_evd` (
  `verify_evd_id` INT NOT NULL,
  `badman_id` VARCHAR(20) NULL,
  `evd_man` VARCHAR(50) NULL,
  `evd_reason` VARCHAR(20) NULL,
  `evd_time` DATETIME NULL,
  `evd_addr` VARCHAR(50) NULL,
  `evd_record` VARCHAR(500) NULL,
  `hand_view` VARCHAR(500) NULL COMMENT '处理意见',
  PRIMARY KEY (`verify_evd_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`warn_msg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`warn_msg` (
  `warn_msg_id` INT NOT NULL,
  `badman_id` VARCHAR(45) NULL COMMENT '矫正人员编号',
  `warn_reason` VARCHAR(45) NULL COMMENT '警告理由',
  `warn_basis` VARCHAR(45) NULL COMMENT '警告根据',
  `office_proposer` VARCHAR(45) NULL COMMENT '所申请人',
  `office_apply_time` VARCHAR(45) NULL COMMENT '所申请时间',
  `office_auditor` VARCHAR(45) NULL,
  `office_audit_time` VARCHAR(45) NULL,
  `office_audit_view` VARCHAR(45) NULL,
  `higher_auditor` VARCHAR(45) NULL,
  `higher_audit_time` VARCHAR(45) NULL,
  `higher_audit_view` VARCHAR(45) NULL,
  PRIMARY KEY (`warn_msg_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
